@angularSkinet_ApiHost_Address = https://localhost:5001

GET {{angularSkinet_ApiHost_Address}}/api/products?sort=priceAsc
Accept: application/json

###

GET {{angularSkinet_ApiHost_Address}}/api/products/brands
Accept: application/json

###

GET {{angularSkinet_ApiHost_Address}}/api/products/types
Accept: application/json

###

GET {{angularSkinet_ApiHost_Address}}/api/products/19
Accept: application/json

###

POST  {{angularSkinet_ApiHost_Address}}/api/products
Content-Type: application/json
Accept: application/json

{
    "name": "prueba",
    "description": "description",
    "price": 100.50,
    "pictureUrl": "ejemplo",
    "type": "Shoe",
    "brand": "Angular",
    "quantityInStock": 100
}

###

PUT {{angularSkinet_ApiHost_Address}}/api/products/19
Content-Type: application/json
Accept: application/json

{
    "id": 19,
    "name": "pruebaxxxxxx",
    "description": "descriptionxxxxx",
    "price": 200.50,
    "pictureUrl": "ejemploxxxxx",
    "type": "Shoexxxxx",
    "brand": "Angularxxxxxx",
    "quantityInStock": 1000
}

###

DELETE  {{angularSkinet_ApiHost_Address}}/api/products/19
Accept: application/json